name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Configure PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.3"
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Composer install
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Compile assets
        run: npm install

      - name: Create deployment artifacts
        run: tar -czf "${{ github.workspace }}/${{ github.sha }}.tar.gz" --exclude=*.git --exclude=node_modules *

      - name: Verify artifact creation
        run: |
          ls -lh "${{ github.workspace }}/${{ github.sha }}.tar.gz" || echo "Artifact ${{ github.sha }}.tar.gz not found"

      - name: Store artifacts for deployments
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: "${{ github.workspace }}/${{ github.sha }}.tar.gz"
          if-no-files-found: warn
