name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Configure PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.3"
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Composer install
        run: |
          composer install --no-dev --no-interaction --prefer-dist

      - name: Compile assets
        run: npm install

      - name: Create deployment artifacts
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          tar -czf "${GITHUB_SHA}.tar.gz" --exclude=*.git --exclude=node_modules *

      - name: Store artifacts for deployments
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: "${GITHUB_SHA}.tar.gz"

